# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: root_app
    build: .
    command: uwsgi --http 0.0.0.0:5000 --module root_app.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/root_app.db
    volumes:
      - ./root_app:/code/root_app
      - ./db/:/db/
    ports:
      - "5000:5000"
